[workspace]
members = [
  "crates/domain",
  "crates/application",
  "crates/infrastructure",
  "crates/web",
  "crates/cli",
  "crates/shared"
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.9.0"
description = "arknights asset storage"
homepage = "https://asset-storage.prts.wiki"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
missing_errors_doc = { level = "allow", priority = 1 }
missing_panics_doc = { level = "allow", priority = 1 }
module_name_repetitions = { level = "allow", priority = 1 }

[workspace.dependencies]
serde = { version = "1.0.219", features = [ "derive" ] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = [
  "signal",
  "rt-multi-thread" 
] }
async-trait = "0.1.88"
tracing = "0.1.41"
chrono = "0.4.41"
validator = { version = "0.20.0" }
clap = { version = "4.5.39", features = [ "derive" ] }
axum = { version = "0.8.4", features = [
  "macros",
  "multipart" 
] }
bytes = { version = "1.10.1" }
rust-embed = "8.7.2"
uuid = { version = "1.17.0", features = [ "v4" ] }
tracing-subscriber = { version = "0.3.19", features = [
  "env-filter",
  "json" 
] }
reqwest = { version = "0.12.19", features = [ "json" ] }
zip = "4.0.0"
anyhow = "1.0.98"
tower-http = { version = "0.6.6", features = [
  "timeout",
  "trace",
  "cors",
  "compression-full" 
] }
thiserror = "2.0.12"
toml = "0.8.22"
lettre = { version = "0.11.16", features = [ "tokio1-native-tls" ] }
serde_variant = "0.1.3"
object_store = { version = "0.12.1", features = [ "aws" ] }
sha256 = "1.6.0"
utoipa = { version = "5.3.1", features = [
  "debug",
  "axum_extras" 
] }
utoipa-axum = { version = "0.2.0", features = [ "debug" ] }
utoipa-scalar = { version = "0.3.0", features = [ "axum" ] }
itertools = "0.14.0"
mime_guess = { version = "2.0.5" }
derive_more = { version = "2.0.1", features = [
  "deref",
  "deref_mut",
  "display" 
] }
sqlx = { version = "0.8.6", features = [
  "runtime-tokio",
  "postgres",
  "tls-rustls" 
] }
sentry = { version = "0.38.1", features = [
  "tracing",
  "tower",
  "tower-axum-matched-path",
  "tower-http" 
] }
tower = "0.5.2"
time = { version = "0.3.41", features = [
  "serde",
  "serde-well-known" 
] }
jsonwebtoken = "9.3.1"
ring = "0.17.14"
rand_chacha = "0.9.0"
rand_core = { version = "0.9.3", features = [ "os_rng" ] }
futures = "0.3.31"
