services:
  db:
    image: postgres:17.6
    restart: unless-stopped
    ports:
      - 25432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  rustfs:
    image: rustfs/rustfs:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      RUSTFS_ADDRESS: "0.0.0.0:9000"
      RUSTFS_CONSOLE_ADDRESS: "0.0.0.0:9001"
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_ACCESS_KEY: torappu
      RUSTFS_SECRET_KEY: torappu123
    volumes:
      - rustfs_data:/data
    command: ["/data"]
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 3s
      timeout: 5s
      retries: 30

volumes:
  postgres-data:
  rustfs_data:
