services:
  db:
    image: postgres:14.8
    restart: unless-stopped
    ports:
      - 25432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - minio_data:/data
    ports:
      - 29000:9000
      - 29001:9001

volumes:
  postgres-data:
  minio_data:
