# Application logging configuration
[logger]
enable = true
level = "debug"
format = "compact"
# override_filter = "trace"  # Uncomment to override filters

# Web server configuration
[server]
port = 25150
host = "http://localhost"

# Mailer Configuration
[mailer.smtp]
host = "smtp.example.com"
port = 465
from_email = "sender@example.com"
to_email = "receiver@example.com"
frontend_url = "http://localhost:25150/"

auth.user = "user@example.com"  # Uncomment and add SMTP user
auth.password = "password"  # Uncomment and add SMTP password

# Database Configuration
[database]
uri = "postgres://ak:ak@localhost:25432/ak_asset_storage_next"

[ak]
asset_url = "https://ak.hycdn.cn/assetbundle/official/Android/assets"
conf_url = "https://ak-conf.hypergryph.com/config/prod/official/Android"

[s3]
endpoint = "http://127.0.0.1:29000"
bucket_name = "arknights-assets"
access_key_id = "access_key_id"
secret_access_key = "secret_access_key"
with_virtual_hosted_style_request = false

# Optional Torappu configuration
[torappu]
token = "your-torappu-token-here"
assetBasePath = "/assets"

# Optional Docker configuration for launching containers on new version detection
[torappu.docker]
enabled = false
image_url = "your-docker-image:latest"
container_name = "ak-asset-container"
env_vars = [
    "CLIENT_VERSION=${CLIENT_VERSION}",
    "RES_VERSION=${RES_VERSION}",
    "DATABASE_URL=postgres://ak:ak@localhost:25432/ak_asset_storage_next"
]
port_mapping = "8080:80"
volume_mapping = "./data:/app/data"
restart_policy = "unless-stopped"
# docker_host = "tcp://localhost:2376"  # Uncomment to use remote Docker daemon
