_default:
  @just --list -u

init: init-env
    cargo binstall cargo-release git-cliff
    cargo install sqlx-cli rustfs-cli

# one-time dev environment prep: kubeconfig, directories, config, upload bucket
init-env: gen-config
    #!/usr/bin/env bash
    set -euo pipefail
    # k3s's kubectl can use /etc/rancher/k3s/k3s.yaml implicitly; kube-rs cannot.
    # Keep an explicit KUBECONFIG or an existing standard kubeconfig untouched.
    if [[ -z "${KUBECONFIG:-}" && ! -e "$HOME/.kube/config" && ! -L "$HOME/.kube/config" ]]; then
        if command -v kubectl >/dev/null 2>&1 && kubectl config current-context >/dev/null 2>&1; then
            mkdir -p "$HOME/.kube"
            kubeconfig_tmp="$(mktemp "$HOME/.kube/config.XXXXXX")"
            trap 'rm -f "$kubeconfig_tmp"' EXIT
            kubectl config view --raw --minify --flatten > "$kubeconfig_tmp"
            mv "$kubeconfig_tmp" "$HOME/.kube/config"
        else
            echo "note: no kubectl context yet; rerun 'just init-env' after k3s is set up to export ~/.kube/config"
        fi
    fi
    # RustFS (k3s, hostPath) writes into tmp/rustfs-data as UID 10001; a fresh
    # checkout must fix ownership and the SELinux label before the first apply.
    mkdir -p tmp/rustfs-data
    if [[ "$(stat -c %u tmp/rustfs-data)" != 10001 ]]; then
        sudo chown -R 10001:10001 tmp/rustfs-data
    fi
    if command -v selinuxenabled >/dev/null 2>&1 && selinuxenabled \
        && [[ "$(stat -c %C tmp/rustfs-data)" != *container_file_t* ]]; then
        sudo chcon -Rt container_file_t tmp/rustfs-data
    fi
    # the bucket must exist before the first upload; the code never creates it
    # (RustFS runs in the local k3s via just k3s-apply, NodePort 31000)
    if command -v rc >/dev/null 2>&1 && curl -sf -m 3 http://127.0.0.1:31000/health >/dev/null; then
        rc alias set rustfs http://127.0.0.1:31000 torappu torappu123 >/dev/null
        rc bucket create --ignore-existing rustfs/arknights-assets
    else
        echo "note: rustfs not reachable; after 'just k3s-apply' run:"
        echo "  rc alias set rustfs http://127.0.0.1:31000 torappu torappu123"
        echo "  rc bucket create --ignore-existing rustfs/arknights-assets"
    fi

# generate tmp/config.toml if absent; host_path is resolved via realpath tmp/asset
gen-config:
    #!/usr/bin/env bash
    set -euo pipefail
    if [[ -e tmp/config.toml ]]; then
        echo "note: tmp/config.toml exists; delete it to regenerate"
        exit 0
    fi
    mkdir -p tmp/asset/asset/gamedata tmp/asset/asset/raw
    asset_root="$(realpath tmp/asset)"
    cat > tmp/config.toml <<EOF
    # Local dev environment config, generated by 'just init-env' (see DEVELOPMENT.md).
    # Server: cargo run -- server -c tmp/config.toml   (port 5150, matches pnpm dev proxy)
    # Worker: cargo run -- worker -c tmp/config.toml
    # Application paths are relative to the repository root; run commands there.
    # Kubernetes host_path was resolved by the generator: after moving the
    # checkout or changing the tmp/asset symlink, delete this file and rerun.

    [logger]
    enable = true
    level = "debug"
    format = "compact"

    [server]
    binding = "localhost"
    port = 5150
    host = "http://localhost"

    [database]
    uri = "postgres://ak:ak@localhost:32432/ak_asset_storage_next"

    [ak]
    asset_url = "https://ak.hycdn.cn/assetbundle/official/Android/assets"
    conf_url = "https://ak-conf.hypergryph.com/config/prod/official/Android"

    [s3]
    endpoint = "http://127.0.0.1:31000"
    bucket_name = "arknights-assets"
    access_key_id = "torappu"
    secret_access_key = "torappu123"
    with_virtual_hosted_style_request = false

    # Blackhole DSN so local errors never reach a real Sentry project.
    [sentry]
    dsn = "https://test@127.0.0.1:9/1"
    traces_sample_rate = 0.0

    # MCP endpoint on http://localhost:5150/mcp (read-only queries).
    [mcp]
    enable = true

    [torappu]
    token = "your-torappu-token-here"
    # tmp/asset is the Torappu storage root (including assetbundle/ and
    # hot_update_list/); extracted resources live in its asset/ subdirectory.
    asset_base_path = "tmp/asset/asset"
    search_concurrency = 4

    # plocate must be installed; the first index build runs at server startup.
    # Lives in /tmp so no setup step is needed: the server creates the directory,
    # and a wiped index is rebuilt on the next start (searches 503 until then).
    [torappu.plocate]
    update_interval_seconds = 600
    database_path = "/tmp/ak-asset-storage/plocate.db"

    # Local server/worker use \$KUBECONFIG / ~/.kube/config, like kubectl.
    # The public main image follows Torappu development; no pull Secret is needed.
    [torappu.kubernetes]
    image_url = "ghcr.io/mooncellwiki/torappu:main"
    namespace = "ak-dev"
    job_name = "ak-asset-job-dev"
    env_vars = [
        "TZ=Asia/Shanghai",
        "ENVIRONMENT=debug",
        "STORAGE_DIR=/app/storage",
        "SENTRY_DSN=https://test@127.0.0.1:9/1",
    ]

    # Single-node k3s hostPath mount, resolved from realpath tmp/asset at
    # generation time (tmp/asset may be a symlink to the Torappu checkout).
    [[torappu.kubernetes.volume_mounts]]
    host_path = "${asset_root}"
    mount_path = "/app/storage"
    EOF

# regenerate tmp/k3s/rustfs.yaml: RustFS bound to this checkout via hostPath;
# applied by k3s-apply and by the e2e suite, so do not edit by hand
gen-rustfs:
    #!/usr/bin/env bash
    set -euo pipefail
    if [[ ! -d tmp/rustfs-data ]]; then
        echo "error: tmp/rustfs-data missing; run 'just init-env' first" >&2
        exit 1
    fi
    data_dir="$(realpath tmp/rustfs-data)"
    mkdir -p tmp/k3s
    cat > tmp/k3s/rustfs.yaml <<EOF
    # Generated by 'just gen-rustfs' — do not edit; rerun to regenerate.
    # S3-compatible object storage; the whole store lives in this checkout's
    # tmp/rustfs-data (hostPath), so the data survives cluster rebuilds.
    # Credentials match tmp/config.toml (torappu/torappu123).
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: rustfs
      namespace: ak-dev
    spec:
      replicas: 1
      strategy:
        type: Recreate
      selector:
        matchLabels:
          app: rustfs
      template:
        metadata:
          labels:
            app: rustfs
        spec:
          automountServiceAccountToken: false
          enableServiceLinks: false
          containers:
            - name: rustfs
              image: rustfs/rustfs:latest
              args: [/data]
              env:
                - name: RUSTFS_ADDRESS
                  value: 0.0.0.0:9000
                - name: RUSTFS_CONSOLE_ADDRESS
                  value: 0.0.0.0:9001
                - name: RUSTFS_CONSOLE_ENABLE
                  value: "true"
                - name: RUSTFS_ACCESS_KEY
                  value: torappu
                - name: RUSTFS_SECRET_KEY
                  value: torappu123
              ports:
                - name: api
                  containerPort: 9000
                - name: console
                  containerPort: 9001
              readinessProbe:
                httpGet:
                  path: /health
                  port: api
                periodSeconds: 5
              volumeMounts:
                - name: data
                  mountPath: /data
          volumes:
            - name: data
              hostPath:
                # hostPath must be absolute on the node; substituted by the generator
                path: ${data_dir}
                type: Directory
    ---
    # API on NodePort 31000, console on 31001, bound to 127.0.0.1 only.
    apiVersion: v1
    kind: Service
    metadata:
      name: rustfs
      namespace: ak-dev
    spec:
      type: NodePort
      selector:
        app: rustfs
      ports:
        - name: api
          port: 9000
          targetPort: api
          nodePort: 31000
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: rustfs-console
      namespace: ak-dev
    spec:
      type: NodePort
      selector:
        app: rustfs
      ports:
        - name: console
          port: 9001
          targetPort: console
          nodePort: 31001
    EOF

# apply the dev dependencies to the local k3s: PostgreSQL from deploy/k3s/dev
# plus the generated RustFS manifest (tmp/k3s/rustfs.yaml)
k3s-apply: gen-rustfs
    #!/usr/bin/env bash
    set -euo pipefail
    kubectl apply -k deploy/k3s/dev
    kubectl apply -f tmp/k3s/rustfs.yaml

up:
    sqlx migrate run

pre-release version:
    git cliff -o CHANGELOG.md --tag {{version}} && git add CHANGELOG.md

e2e:
    cargo test --test e2e -- --ignored --nocapture --test-threads=1
