/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/asset/': RouteRecordInfo<
      '/asset/',
      '/asset',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/asset/components/AssetContent': RouteRecordInfo<
      '/asset/components/AssetContent',
      '/asset/components/AssetContent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/asset/components/AssetTree': RouteRecordInfo<
      '/asset/components/AssetTree',
      '/asset/components/AssetTree',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/AssetMappingDetailModal': RouteRecordInfo<
      '/components/AssetMappingDetailModal',
      '/components/AssetMappingDetailModal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/FileDetail': RouteRecordInfo<
      '/components/FileDetail',
      '/components/FileDetail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/FileDetailDiff': RouteRecordInfo<
      '/components/FileDetailDiff',
      '/components/FileDetailDiff',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/diff': RouteRecordInfo<
      '/diff',
      '/diff',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/file/': RouteRecordInfo<
      '/file/',
      '/file',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manifest/': RouteRecordInfo<
      '/manifest/',
      '/manifest',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manifest/components/ManifestContent': RouteRecordInfo<
      '/manifest/components/ManifestContent',
      '/manifest/components/ManifestContent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manifest/components/ManifestTree': RouteRecordInfo<
      '/manifest/components/ManifestTree',
      '/manifest/components/ManifestTree',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'app/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'app/pages/asset/index.vue': {
      routes:
        | '/asset/'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/pages/asset/components/AssetContent.vue': {
      routes:
        | '/asset/components/AssetContent'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/pages/asset/components/AssetTree.vue': {
      routes:
        | '/asset/components/AssetTree'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/pages/components/AssetMappingDetailModal.vue': {
      routes:
        | '/components/AssetMappingDetailModal'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/pages/components/FileDetail.vue': {
      routes:
        | '/components/FileDetail'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/pages/components/FileDetailDiff.vue': {
      routes:
        | '/components/FileDetailDiff'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/pages/diff.vue': {
      routes:
        | '/diff'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/pages/file/index.vue': {
      routes:
        | '/file/'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/pages/manifest/index.vue': {
      routes:
        | '/manifest/'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/pages/manifest/components/ManifestContent.vue': {
      routes:
        | '/manifest/components/ManifestContent'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/pages/manifest/components/ManifestTree.vue': {
      routes:
        | '/manifest/components/ManifestTree'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
