/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/asset/': RouteRecordInfo<'/asset/', '/asset', Record<never, never>, Record<never, never>>,
    '/asset/components/AssetContent': RouteRecordInfo<'/asset/components/AssetContent', '/asset/components/AssetContent', Record<never, never>, Record<never, never>>,
    '/asset/components/AssetTree': RouteRecordInfo<'/asset/components/AssetTree', '/asset/components/AssetTree', Record<never, never>, Record<never, never>>,
    '/components/FileDetail': RouteRecordInfo<'/components/FileDetail', '/components/FileDetail', Record<never, never>, Record<never, never>>,
    '/components/FileDetailDiff': RouteRecordInfo<'/components/FileDetailDiff', '/components/FileDetailDiff', Record<never, never>, Record<never, never>>,
    '/diff': RouteRecordInfo<'/diff', '/diff', Record<never, never>, Record<never, never>>,
    '/file/': RouteRecordInfo<'/file/', '/file', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'app/pages/index.vue': {
      routes: '/'
      views: never
    }
    'app/pages/[...all].vue': {
      routes: '/[...all]'
      views: never
    }
    'app/pages/asset/index.vue': {
      routes: '/asset/'
      views: never
    }
    'app/pages/asset/components/AssetContent.vue': {
      routes: '/asset/components/AssetContent'
      views: never
    }
    'app/pages/asset/components/AssetTree.vue': {
      routes: '/asset/components/AssetTree'
      views: never
    }
    'app/pages/components/FileDetail.vue': {
      routes: '/components/FileDetail'
      views: never
    }
    'app/pages/components/FileDetailDiff.vue': {
      routes: '/components/FileDetailDiff'
      views: never
    }
    'app/pages/diff.vue': {
      routes: '/diff'
      views: never
    }
    'app/pages/file/index.vue': {
      routes: '/file/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
