ALTER TABLE versions ALTER COLUMN res SET NOT NULL;
ALTER TABLE versions ALTER COLUMN client SET NOT NULL;
ALTER TABLE versions ALTER COLUMN is_ready SET NOT NULL;
ALTER TABLE versions ALTER COLUMN hot_update_list SET NOT NULL;

ALTER TABLE files ALTER COLUMN hash SET NOT NULL;
ALTER TABLE files ALTER COLUMN size SET NOT NULL;

ALTER TABLE bundles ALTER COLUMN path SET NOT NULL;
ALTER TABLE bundles ALTER COLUMN version SET NOT NULL;
ALTER TABLE bundles ALTER COLUMN file SET NOT NULL;
